# Generated by Django 5.2.8 on 2025-11-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(default=1, upload_to='Movies/Covers'),
            preserve_default=False,
        ),
    ]
